version: '3.5'
services:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - CELERY_BROKER_URL=amqp://user:password@broker:5672
      - CELERY_RESULT_BACKEND=rpc://
    ports:
      - "8000:8000"
    depends_on:
      - broker

  worker:
    build: .
    command: celery -A idare worker -B -l INFO
    environment:
      - CELERY_BROKER_URL=amqp://user:password@broker:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - broker

  broker:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
    restart: on-failure